runtime: python27
api_version: 1
threadsafe: true
inbound_services:
- channel_presence
- xmpp_message

handlers:
- url: /
  script: backend.main.app
- url: /chat
  static_files: index.html
  upload: index.html
- url: /dist
  static_dir: frontend/dist/
# TODO: Secure this connection
- url: /api/.*
  script: backend.api.app
- url: /_ah/.*
  script: backend.api.app
- url: /.*
  script: backend.main.app
