runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /dist
  static_dir: dist/
- url: /api/.*
  script: api.app
- url: /.*
  script: main.app
