runtime: python27
api_version: 1
threadsafe: true
inbound_services:
- channel_presence

handlers:
- url: /
  script: backend.main.app
- url: /chat
  static_files: index.html
  upload: index.html
- url: /dist
  static_dir: dist/
# TODO: Secure this connection
- url: /api/.*
  script: backend.api.app
- url: /_ah/channel/connected/
  script: backend.api.app
- url: /_ah/channel/disconnected/
  script: backend.api.app
- url: /.*
  script: backend.main.app
